{{- if .Capabilities.APIVersions.Has "extensions/v1beta1" }}
apiVersion: extensions/v1beta1
{{- else if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- end }}
kind: Deployment
metadata:
  name: {{ template "pg-stats.fullname" . }}
  labels:
    app: {{ template "pg-stats.name" . }}
    chart: {{ template "pg-stats.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "pg-stats.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "pg-stats.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers: 
      - name: exporter
        image: wrouesnel/postgres_exporter
        args: ["--extend.query-path", "/queries.yaml"]
        ports:
        - name: http
          containerPort: 9187
          protocol: TCP
        env:
          - name: "DATA_SOURCE_NAME"
            valueFrom:
              secretKeyRef:
                name: {{ template "pg-stats.fullname" . }}-secret
                key: databaseUrl
        volumeMounts:
          - name: config-volume-parameters
            mountPath: /queries.yaml
            subPath: queries.yaml
      volumes:
        - name: config-volume-parameters
          configMap:
            name: {{ template "pg-stats.fullname" . }}-config
