apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pg-stats.fullname" . }}-secret
  labels:
    app: {{ template "pg-stats.name" . }}
    chart: {{ template "pg-stats.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
stringData:
  databaseUrl: {{ .Values.databaseUrl }}
