{
 "title": "Postgres stat indexes",
 "tags": [ "postgres" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "query": "label_values(server)" },
   {
    "name": "schema",
    "query": "label_values(pg_stat_user_tables_analyze_count{server=\"$server\"}, schemaname)"
   },
   {
    "name": "table",
    "query": "label_values(pg_stat_user_tables_analyze_count{schemaname=\"$schema\",server=\"$server\"}}, relname)"
   },
   {
    "name": "index",
    "query": "label_values(pg_stat_user_indexes_idx_scan{schemaname=\"$schema\",relname=\"$table\",server=\"$server\"}, indexrelname)"
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Index scans initiated",
   "type": "graph",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (indexrelname) (rate(pg_stat_user_indexes_idx_scan{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m]))",
     "legendFormat": "{{ indexrelname }}"
    }
   ]
  },
  {
   "title": "Entries & rows returned",
   "type": "graph",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (indexrelname) (rate(pg_stat_user_indexes_idx_tup_fetch{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m]) + rate(pg_stat_user_indexes_idx_tup_read{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m]))",
     "legendFormat": "{{ indexrelname }}"
    }
   ]
  },
  {
   "title": "Block read",
   "type": "graph",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (indexrelname) (rate(pg_statio_user_indexes_idx_blks_read{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m]) + rate(pg_statio_user_indexes_idx_blks_hit{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m]))",
     "legendFormat": "{{ indexrelname }}"
    }
   ]
  },
  { "title": "Index $index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "index" },
  {
   "title": "Index scans initiated",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_indexes_idx_scan{schemaname=\"$schema\", relname=\"$table\", indexrelname=\"$index\",server=\"$server\"}[1m])",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Entries & rows returned",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_indexes_idx_tup_read{schemaname=\"$schema\", relname=\"$table\", indexrelname=\"$index\",server=\"$server\"}[1m])",
     "legendFormat": "index entries returnd"
    },
    {
     "expr": "rate(pg_stat_user_indexes_idx_tup_fetch{schemaname=\"$schema\", relname=\"$table\", indexrelname=\"$index\",server=\"$server\"}[1m])",
     "legendFormat": "rows fetch"
    }
   ]
  },
  {
   "title": "Blocks read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_statio_user_indexes_idx_blks_read{schemaname=\"$schema\", relname=\"$table\", indexrelname=\"$index\",server=\"$server\"}[1m])",
     "legendFormat": "block read"
    },
    {
     "expr": "rate(pg_statio_user_indexes_idx_blks_hit{schemaname=\"$schema\", relname=\"$table\", indexrelname=\"$index\",server=\"$server\"}[1m])",
     "legendFormat": "buffer hits"
    }
   ]
  }
 ]
}