{
 "title": "Postgres stat tables",
 "tags": [ "postgres" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "query": "label_values(server)" },
   {
    "name": "schema",
    "query": "label_values(pg_stat_user_tables_analyze_count{server=\"$server\"}, schemaname)"
   },
   {
    "name": "table",
    "query": "label_values(pg_stat_user_tables_analyze_count{schemaname=\"$schema\",server=\"$server\"}, relname)"
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sequential scans",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (relname) (rate(pg_stat_user_tables_seq_scan{schemaname=\"$schema\",server=\"$server\"}[1m]))",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Live rows fetched by sequential scans",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (relname) (rate(pg_stat_user_tables_seq_tup_read{schemaname=\"$schema\",server=\"$server\"}[1m]))",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Index scans",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (relname) (rate(pg_stat_user_tables_idx_scan{schemaname=\"$schema\",server=\"$server\"}[1m]))",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Live rows fetched by index scans",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (relname) (rate(pg_stat_user_tables_idx_tup_fetch{schemaname=\"$schema\",server=\"$server\"}[1m]))",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Blocks read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (relname) (rate(pg_statio_user_tables_idx_blks_read{schemaname=\"$schema\",server=\"$server\"}[1m]) + rate(pg_statio_user_tables_heap_blks_read{schemaname=\"$schema\",server=\"$server\"}[1m]) + rate(pg_statio_user_tables_tidx_blks_read{schemaname=\"$schema\",server=\"$server\"}[1m]) + rate(pg_statio_user_tables_toast_blks_read{schemaname=\"$schema\",server=\"$server\"}[1m]))",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Buffers hit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (relname) (rate(pg_statio_user_tables_heap_blks_hit{schemaname=\"$schema\",server=\"$server\"}[1m]) + rate(pg_statio_user_tables_idx_blks_hit{schemaname=\"$schema\",server=\"$server\"}[1m]) + rate(pg_statio_user_tables_toast_blks_hit{schemaname=\"$schema\",server=\"$server\"}[1m]) + rate(pg_statio_user_tables_tidx_blks_hit{schemaname=\"$schema\",server=\"$server\"}[1m]))",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Table $table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "table" },
  {
   "title": "Scans",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_seq_scan{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "seq scan"
    },
    {
     "expr": "rate(pg_stat_user_tables_idx_scan{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "idx scan"
    }
   ]
  },
  {
   "title": "Live rows fetched by scans",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_seq_tup_read{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "seq tup read"
    },
    {
     "expr": "rate(pg_stat_user_tables_idx_tup_fetch{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "idx tup fetch"
    }
   ]
  },
  {
   "title": "Write on rows",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_ins{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "Inserted"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_upd{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "Updated"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_hot_upd{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "Hot updated"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_del{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Analyzes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_vacuum_count{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "Vacuum"
    },
    {
     "expr": "rate(pg_stat_user_tables_autovacuum_count{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "Auto vacuum"
    },
    {
     "expr": "rate(pg_stat_user_tables_analyze_count{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "Analyze"
    },
    {
     "expr": "rate(pg_stat_user_tables_autoanalyze_count{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "Auto analyze"
    }
   ]
  },
  {
   "title": "Block reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_statio_user_tables_heap_blks_read{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "disk blocks read"
    },
    {
     "expr": "rate(pg_statio_user_tables_heap_blks_read{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "buffer hits"
    }
   ]
  },
  {
   "title": "Index block reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_statio_user_tables_idx_blks_read{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "disk blocks read"
    },
    {
     "expr": "rate(pg_statio_user_tables_idx_blks_hit{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "buffer hits"
    }
   ]
  },
  {
   "title": "TOAST block reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_statio_user_tables_toast_blks_read{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "disk blocks read"
    },
    {
     "expr": "rate(pg_statio_user_tables_toast_blks_hit{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "buffer hits"
    }
   ]
  },
  {
   "title": "TOAST index block reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_statio_user_tables_tidx_blks_read{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "disk blocks read"
    },
    {
     "expr": "rate(pg_statio_user_tables_tidx_blks_hit{schemaname=\"$schema\", relname=\"$table\",server=\"$server\"}[1m])",
     "legendFormat": "buffer hits"
    }
   ]
  }
 ]
}